services:

  web:
    build: ./frontend
    container_name: "frontend"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 5174:80
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: "backend"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000